### PR TITLE
Adding the Hop router to the app.

### PR DESCRIPTION
**Pull request by rodrigo-morais**
Adding the router to app.

The address `http://localhost:3000/#/coaches/new` is calling the page to add a new `Coach`.
The address `http://localhost:3000/` is calling the `Not Found Page`.
The address `http://localhost:3000/#/coaches/:id/edit` is calling the `Not Found Page`.

This router needs a refactoring after the `Search Page` is added to the app.

### CODE REVIEW

**Comment by rodrigo-morais** [comment]
ping @viniciusffj

**Comment by viniciusffj** [comment]
@rodrigo-morais 

This code breaks the Edit page, the problem is that the model is not updating when the form fields are changed.

This issue is caused due to the following changes:
- The [src/Update.elm](https://github.com/rodrigo-morais/coach-plataform/pull/12/files#diff-6e79f775167692b85fb8131edb39ae4bR22) is cleaning the coach model (`ViewModel`) every time it receives a `CoachesEditAction`.
- The [src/View.elm](https://github.com/rodrigo-morais/coach-plataform/pull/12/files#diff-54bdcd9af0518db764a087160da34d0eR61) is not using the app model to create the edit page, so Elm cannot realize that the view needs to be updated.

I found this issue a little bit abstract, so I [created a branch](https://github.com/rodrigo-morais/coach-plataform/tree/add-hop-router-example) to clarify it. 
This solution still has a problem if you do the following:
1. Go to [http://localhost:3000/#/coaches/new](http://localhost:3000/#/coaches/new) and fill the form.
2. Go to [http://localhost:3000/#/notFound](http://localhost:3000/#/notFound) by changing the browser url.
3. Go back to [http://localhost:3000/#/coaches/new](http://localhost:3000/#/coaches/new) and the data filled on step 1 will still be there. This happens because the coach model (`ViewModel`) is not cleaned when we go back to the new route.

In my option, the coach model needs to be cleaned every time we change the route to `CoachesNewRoute`, but I'm not sure what is the best way to do this.

Anyway, this issue showed how tests can make our life easier, because if we had a test (not sure which type) we would have a faster feedback saying that the code broke the page.

**Comment by rodrigo-morais** [comment]
@viniciusffj 

Yes. When I mentioned that I have to do a refactoring I was thinking in that. I just thought to do it after you add the `Search Page` in the app would be easier. The problem for me is not the new Coach, but the existent one. I can't do the update works to this scenario.
Please, take a look in the last update to see if you have some idea.

**Comment by viniciusffj** [comment]
@rodrigo-morais 

Why do we need this `Coach list`? I can't see a reason behind it. 

In my option the edit page can exists without it. For me, it should do a request to get the coach every time we go to `coaches/:id/edit/`.

I'm confused about this, I don't know why we need this amount of changes to add the router.

**Comment by rodrigo-morais** [comment]
@viniciusffj 

I agree. But in this case we handle the `Coach` as new `Coach`.
To get the existent `Coach` we need a list of `Coaches`. This case was not working, because in each edition we have to update the list of `Coaches`.

I solved the problem, but I'm sure that there is a better solution.

Please, take a look again.

**Comment by rodrigo-morais** [comment]
@viniciusffj 
I removed the `Edit Route` to make it simple, and in the future we can add it as your recommendation.
Please, take a look again.

**Comment by viniciusffj** [comment]
Looks good, merging it.

**Pull request merged**
